name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install poetry
        run: pip install poetry

      - name: install dependencies
        run: poetry install

      - name: run lint checker
        run: poetry run task lint

      - name: run tests
        run: poetry run task test
